;;;; t/test-input.lisp -- typing while the agent works: queue or interrupt.

(in-package :cl-agent)

(defclass steer-frontend (queued-input-mixin)
  ((lines :initform nil :accessor steer-lines)
   (delivered :initform nil :accessor steer-delivered)))
(defmethod ui-system ((frontend steer-frontend) text) (push text (steer-lines frontend)))
(defmethod ui-input-delivered ((frontend steer-frontend) text) (push text (steer-delivered frontend)))

(defclass steer-provider (llm-provider)
  ((script :initarg :script :accessor steer-script)
   (seen :initform nil :accessor steer-seen)))
(defmethod chat ((provider steer-provider) messages tools)
  (declare (ignore tools))
  (push (copy-list messages) (steer-seen provider))
  (funcall (pop (steer-script provider))))

(defun steer-tool-call-message ()
  (list :role "assistant" :content nil
        :tool-calls (list (list :id "c1" :name "test-noop" :arguments (jobj)))))

(defmacro with-noop-tool (&body body)
  `(progn
     (register-tool (make-instance 'tool :name "test-noop" :description "noop"
                                         :handler (lambda (args) (declare (ignore args)) "ok")))
     (unwind-protect (progn ,@body)
       (unregister-tool "test-noop"))))

(defun steer-session (frontend script)
  (make-session (make-instance 'steer-provider :model "m" :script script)
                :frontend frontend :tools (list (find-tool "test-noop"))))

(deftest accept-input-queues-when-busy-and-runs-immediately-when-idle ()
  (let ((frontend (make-instance 'steer-frontend)))
    (check-equal (multiple-value-list (frontend-accept-input frontend "hello")) '(:immediate "hello"))
    (check-equal (multiple-value-list (frontend-accept-input frontend "/interrupt")) '(:ignored nil)
                 "interrupting an idle agent does nothing")
    (setf (frontend-busy-p frontend) t)
    (check-equal (multiple-value-list (frontend-accept-input frontend "first")) '(:queued "first"))
    (check-equal (multiple-value-list (frontend-accept-input frontend "/interrupt do X instead"))
                 '(:queued "do X instead"))
    (check (ui-interrupt-requested-p frontend) "/interrupt TEXT interrupts")
    (check-equal (ui-poll-input frontend) '("first" "do X instead"))
    (check-equal (steer-delivered frontend) '("do X instead" "first"))
    (check-equal (ui-poll-input frontend) nil "polling drains the queue")
    (ui-thinking-stopped frontend)
    (check (not (ui-interrupt-requested-p frontend)) "the flag does not outlive the turn")
    (check (not (frontend-busy-p frontend)))))

(deftest queued-message-reaches-the-model-before-its-next-request ()
  (with-noop-tool
    (let* ((frontend (make-instance 'steer-frontend))
           (session (steer-session
                     frontend
                     (list (lambda ()
                             (frontend-accept-input frontend "also look at X")
                             (steer-tool-call-message))
                           (lambda () (list :role "assistant" :content "done" :tool-calls nil))))))
      (setf (session-messages session)
            (append (session-messages session) (list (list :role "user" :content "start"))))
      (check-equal (getf (run-agent-turn session) :content) "done")
      (let ((second-request (first (steer-seen (session-provider session)))))
        (check (find-if (lambda (m) (and (equal (getf m :role) "user")
                                         (equal (getf m :content) "also look at X")))
                        second-request)
               "the queued message was in the second request"))
      (check-equal (ui-poll-input frontend) nil "nothing is left over"))))

(deftest interrupt-skips-pending-tools-and-ends-the-turn-with-valid-history ()
  (with-noop-tool
    (let* ((frontend (make-instance 'steer-frontend))
           (session (steer-session
                     frontend
                     (list (lambda ()
                             (frontend-accept-input frontend "/interrupt")
                             (steer-tool-call-message))
                           (lambda () (error "the provider must not be called again"))))))
      (setf (session-messages session)
            (append (session-messages session) (list (list :role "user" :content "start"))))
      (check-equal (run-agent-turn session) nil)
      (check-equal (length (steer-script (session-provider session))) 1 "one request only")
      (let ((tool-message (find "tool" (session-messages session) :key (lambda (m) (getf m :role))
                                                                    :test #'equal)))
        (check (search "interrupted" (getf tool-message :content)) "tool call got a result, unrun"))
      (check (member "[interrupted]" (steer-lines frontend) :test #'equal))
      (check (not (ui-interrupt-requested-p frontend))))))

(deftest queued-slash-commands-wait-for-the-repl-loop ()
  (let* ((frontend (make-instance 'steer-frontend))
         (session (make-session (make-instance 'steer-provider :model "m" :script nil)
                                :frontend frontend :tools nil)))
    (setf (frontend-busy-p frontend) t)
    (frontend-accept-input frontend "/stats")
    (frontend-accept-input frontend "hello")
    (check-equal (session-absorb-queued-input session) '("hello"))
    (check-equal (session-deferred-input session) '("/stats"))
    (check-equal (getf (car (last (session-messages session))) :content) "hello")))

(deftest interrupt-stops-a-running-shell-command-promptly ()
  (let* ((frontend (make-instance 'steer-frontend))
         (session (make-session (make-instance 'steer-provider :model "m" :script nil)
                                :frontend frontend :tools nil))
         (*current-session* session)
         (start (get-internal-real-time)))
    (setf (frontend-busy-p frontend) t)
    (frontend-request-interrupt frontend)
    (let ((result (call-tool "shell" (jobj "command" "sleep 30" "reason" "test" "result_use" "none"
                                            "expected_seconds" 60))))
      (check (search "interrupted the turn" result))
      (check (< (/ (- (get-internal-real-time) start) internal-time-units-per-second) 10)
             "returned long before the sleep ended"))))

(deftest cli-reader-queues-input-typed-during-a-turn ()
  (let ((frontend (make-instance 'cli-frontend)))
    (setf (frontend-busy-p frontend) t)
    (let ((*standard-output* (make-broadcast-stream)))
      (cli-read-loop frontend (make-string-input-stream (format nil "a~%/interrupt~%b~%"))))
    (check-equal (ui-poll-input frontend) '("a" "b"))
    (check (ui-interrupt-requested-p frontend))
    (check-equal (trivial-channels:recvmsg (cli-frontend-lines frontend)) nil "end of input")))

(deftest tui-and-web-show-queued-messages ()
  (let ((model (make-instance 'tui-chat-model :input-channel nil)))
    (setf (tui-chat-queued model) '("one" "two"))
    (check (search "Queued (2)" (first (tui-queue-panel-lines model))))
    (check (search "› one" (second (tui-queue-panel-lines model)))))
  (let ((frontend (make-instance 'web-frontend)))
    (setf (frontend-busy-p frontend) t)
    (frontend-accept-input frontend "later")
    (check-equal (jget (json-decode (web-frontend-status-json frontend)) "queued") '("later"))
    (ui-poll-input frontend)
    (check-equal (jget (json-decode (web-frontend-status-json frontend)) "queued") nil)
    (check (search "id=\"stop\"" *web-page-html*))
    (check (search "renderQueued(data.queued||[])" *web-page-html*))))
