(in-package :cl-agent)

(deftest notify-hooks-run-in-order ()
  (clear-hooks :test-point)
  (let ((seen nil))
    (add-hook :test-point 'a (lambda () (push :a seen)))
    (add-hook :test-point 'b (lambda () (push :b seen)))
    (run-hook :test-point)
    (check-equal (nreverse seen) '(:a :b)))
  (clear-hooks :test-point))

(deftest notify-hook-prepended-with-append-nil ()
  (clear-hooks :test-point)
  (let ((seen nil))
    (add-hook :test-point 'a (lambda () (push :a seen)))
    (add-hook :test-point 'b (lambda () (push :b seen)) :append nil)
    (run-hook :test-point)
    (check-equal (nreverse seen) '(:b :a)))
  (clear-hooks :test-point))

(deftest notify-hook-error-does-not-stop-others ()
  (clear-hooks :test-point)
  (let ((ran nil))
    (add-hook :test-point 'boom (lambda () (error "boom")))
    (add-hook :test-point 'after (lambda () (setf ran t)))
    (run-hook :test-point)
    (check ran "second hook still ran after the first signalled"))
  (clear-hooks :test-point))

(deftest re-adding-same-name-replaces ()
  (clear-hooks :test-point)
  (add-hook :test-point 'x (lambda () 1))
  (add-hook :test-point 'x (lambda () 2))
  (check-equal (length (list-hooks :test-point)) 1 "second add replaced, not stacked")
  (clear-hooks :test-point))

(deftest remove-hook-removes-exactly-one ()
  (clear-hooks :test-point)
  (add-hook :test-point 'x (lambda () 1))
  (add-hook :test-point 'y (lambda () 2))
  (check (remove-hook :test-point 'x))
  (check-equal (list-hooks :test-point) '(y))
  (check-equal (remove-hook :test-point 'x) nil "removing again returns nil")
  (clear-hooks :test-point))

(deftest chain-hook-threads-value ()
  (clear-hooks :test-chain)
  (add-hook :test-chain 'double (lambda (n) (* n 2)))
  (add-hook :test-chain 'add-one (lambda (n) (1+ n)))
  (check-equal (run-hook-chain :test-chain 5) 11 "(5*2)+1")
  (clear-hooks :test-chain))

(deftest chain-hook-error-propagates ()
  (clear-hooks :test-chain)
  (add-hook :test-chain 'boom (lambda (n) (declare (ignore n)) (error "nope")))
  (check-condition error (run-hook-chain :test-chain 1))
  (clear-hooks :test-chain))

(deftest chain-hook-with-no-registrations-is-identity ()
  (clear-hooks :test-chain)
  (check-equal (run-hook-chain :test-chain '(:a 1)) '(:a 1)))
