(in-package :cl-agent)

(deftest dispatch-slash-command-not-a-command-passthrough ()
  (let ((session (make-session (make-instance 'ollama-provider))))
    (check-equal (dispatch-slash-command session "hello there") :not-a-command)))

(deftest dispatch-slash-command-unknown-command-keeps-repl-running ()
  (let ((session (make-session (make-instance 'ollama-provider))))
    (check (dispatch-slash-command session "/definitely-not-a-real-command"))))

(deftest slash-exit-and-quit-return-nil ()
  (let ((session (make-session (make-instance 'ollama-provider))))
    (check-equal (dispatch-slash-command session "/exit") nil)
    (check-equal (dispatch-slash-command session "/quit") nil)))

(deftest slash-call-invokes-a-tool-with-json-args ()
  (let ((session (make-session (make-instance 'ollama-provider)))
        (output (make-string-output-stream)))
    (let ((*standard-output* output))
      (dispatch-slash-command session "/call shell {\"command\": \"echo slash-call-test-marker\"}"))
    (check (search "slash-call-test-marker" (get-output-stream-string output)))))

(deftest slash-call-with-no-args-defaults-to-empty-object ()
  (define-tool test-repl-no-args-tool (args) (:description "d") (format nil "~d keys" (hash-table-count args)))
  (let ((session (make-session (make-instance 'ollama-provider)))
        (output (make-string-output-stream)))
    (let ((*standard-output* output))
      (dispatch-slash-command session "/call test-repl-no-args-tool"))
    (check (search "0 keys" (get-output-stream-string output))))
  (unregister-tool "test-repl-no-args-tool"))

(deftest slash-call-unknown-tool-reports-error-not-condition ()
  (let ((session (make-session (make-instance 'ollama-provider)))
        (output (make-string-output-stream)))
    (let ((*standard-output* output))
      (check (dispatch-slash-command session "/call no-such-tool-xyz {}")))
    (check (search "[error]" (get-output-stream-string output)))))

(deftest slash-tools-lists-session-tools ()
  (let* ((session (make-session (make-instance 'ollama-provider) :tools (list (find-tool "shell"))))
         (output (make-string-output-stream)))
    (let ((*standard-output* output))
      (dispatch-slash-command session "/tools"))
    (check (search "shell" (get-output-stream-string output)))))
