(in-package :cl-agent)

(deftest lsp-configuration-is-discovered-without-starting-a-server ()
  (with-temp-config-dir ()
    (let ((*lsp-configuration-pathname* (merge-pathnames "lsp.sexp" *config-directory*)))
      (ensure-config-directory)
      (with-open-file (out *lsp-configuration-pathname* :direction :output :if-exists :supersede)
        (write-string "(:version 1 :servers ((:name \"clang\" :command \"clangd\" :extensions (\".c\") :language-id \"c\")))" out))
      (multiple-value-bind (available unavailable) (initialize-lsp)
        (declare (ignore unavailable))
        (check (some (lambda (server)
                       (string= (cl-lsp:lsp-server-configuration-name server) "clang"))
                     available)))
      (check (find-tool "lsp-query"))
      (check (find-tool "lsp-diagnostics"))
      (close-lsp-servers))))
