#!/bin/sh -e
# scripts/build-clspec-data.sh -- (re)generate data/cl-spec.sdoc.
#
# data/cl-spec.sdoc is a pre-built, committed data file (an "sdoc", see
# https://codeberg.org/dlowe/metaspectre's doc/output-spec.md): the
# ANSI Common Lisp draft standard (dpANS3) parsed into plain
# s-expressions. cl-agent's `lookup-cl-spec` tool (src/clspec.lisp)
# reads it directly at runtime with READ -- no dependency on
# metaspectre, alexandria, cl-ppcre, or stencl at agent runtime, only
# at *this* one-time (or occasional) regeneration step.
#
# Most people never need to run this script -- data/cl-spec.sdoc is
# already committed. Run it only to pick up upstream errata/patches to
# the spec text, by bumping METASPECTRE_REF below and re-running.
#
# What it does:
#   1. Shallow-clones metaspectre (pinned to METASPECTRE_REF) into
#      vendor/metaspectre/ (gitignored -- this is a build tool, not a
#      runtime dependency, so it is not kept around).
#   2. Writes a throwaway ASDF system into that checkout which loads
#      only the four files convert-whole-spec actually needs
#      (package/output/parser/biblinks/patch) -- deliberately skipping
#      render.lisp/texinfo.lisp/elpa.lisp/issues.lisp, which pull in
#      `stencl`, a templating library that (per metaspectre's own
#      README) isn't published anywhere ocicl/Quicklisp can fetch it
#      from. We don't need HTML rendering, just the parsed data.
#   3. Runs (metaspectre::convert-whole-spec), which parses
#      vendor/metaspectre/external/dpANS3/chap-*.tex (bundled in the
#      metaspectre repo already -- no separate spec-source download)
#      into vendor/metaspectre/out/sdoc/metaspec.sdoc.
#   4. Copies that file to data/cl-spec.sdoc.

cd "$(dirname "$0")/.."
PROJECT_ROOT="$(pwd)"
VENDOR_DIR="$PROJECT_ROOT/vendor/metaspectre"
METASPECTRE_REF="${METASPECTRE_REF:-108544f2e5f483571522f9aa52e6097f47d0c0f1}"

if [ ! -d "$VENDOR_DIR" ]; then
	mkdir -p "$PROJECT_ROOT/vendor"
	git clone https://codeberg.org/dlowe/metaspectre/ "$VENDOR_DIR"
fi
(cd "$VENDOR_DIR" && git fetch --quiet origin "$METASPECTRE_REF" 2>/dev/null || true
 cd "$VENDOR_DIR" && git checkout --quiet "$METASPECTRE_REF")

cat >"$VENDOR_DIR/metaspectre-convert-only.asd" <<'EOF'
;; Generated by scripts/build-clspec-data.sh -- loads just enough of
;; metaspectre to run convert-whole-spec, without the unpublished
;; `stencl` dependency that only render.lisp/texinfo.lisp/elpa.lisp
;; need. See that script for why.
(asdf:defsystem #:metaspectre-convert-only
  :depends-on (#:alexandria #:cl-ppcre)
  :components ((:module :src :components
                        ((:file "package")
                         (:file "output")
                         (:file "parser")
                         (:file "biblinks")
                         (:file "patch")))))
EOF

(cd "$VENDOR_DIR" && touch ocicl.csv && ocicl install alexandria cl-ppcre)

sbcl --non-interactive \
	--eval "(let ((rt (merge-pathnames \".local/share/ocicl/ocicl-runtime.lisp\" (user-homedir-pathname)))) (when (probe-file rt) (load rt)))" \
	--eval "(asdf:initialize-source-registry (list :source-registry (list :directory \"$VENDOR_DIR/\") :inherit-configuration))" \
	--eval '(asdf:load-system "metaspectre-convert-only")' \
	--eval '(metaspectre::convert-whole-spec)'

cp "$VENDOR_DIR/out/sdoc/metaspec.sdoc" "$PROJECT_ROOT/data/cl-spec.sdoc"
echo "wrote $PROJECT_ROOT/data/cl-spec.sdoc ($(wc -c <"$PROJECT_ROOT/data/cl-spec.sdoc") bytes)"
